#!/usr/bin/env python
import random
try:
	num = raw_input("how many problems? ")
	num = int(num)
	if type(num) == int:
		answers = []
		for i in xrange(num):
			num1 = random.uniform(2.0,10.0)
			num2 = random.uniform(2.0,10.0)
			print ("%.2f x %.2f = " % (num1, num2))
			answers.append(num1*num2)
		raw_input("Press Enter for answers...")
		for a in answers:
			print ("%0.2f" % (a))
	else:
		print ("not a whole number, you bad egg!")
except:
		print ("not a number, you bad egg!")