#!/usr/bin/env python
import random
try:
	num = raw_input("how many problems? ")
	num = int(num)
	if type(num) == int:
		answers = []
		for i in xrange(num):
			num1 = int(random.uniform(10,50))
			num2 = int(random.uniform(100,500))
			print ("%d / %d = " % (num1, num2))
			answers.append(float(num1) / float(num2))
		raw_input("Press Enter for answers...")
		for a in answers:
			print ("%0.2f" % (a))
	else:
		print ("not a whole number, you bad egg!")
except:
		print ("not a number, you bad egg!")